# .github/release-drafter.yml
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: ':rocket: Features'
    labels:
      - feature
      - enhancement
  - title: ':bug: Bug Fixes'
    labels:
      - bug
  - title: ':package: Dependencies'
    labels:
      - dependencies
  - title: ':page_facing_up: Documentation'
    labels:
      - docs

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Changes
  $CHANGES
  ## Contributors
  Thanks to the following people who contributed to this release:
  $CONTRIBUTORS
