 name: Generate Release Notes
     on:
       push:
         tags:
           - "v*.*.*"
     jobs:
       generate_release_notes:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout Code
             uses: actions/checkout@v2
           - name: Generate Release Notes
             uses: mikepenz/release-changelog-builder-action@v2
             with:
               configuration: .github/release-drafter.yml
           - name: Create GitHub Release
             uses: ncipollo/release-action@v1
             with:
               token: ${{ secrets.GITHUB_TOKEN }}
               name: Release ${{ github.ref_name }}
               tag_name: ${{ github.ref_name }}
               files: |
                 CHANGELOG.md
                 RELEASE_NOTES.md
